# Generated by Django 6.0.2 on 2026-02-25 12:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория теста',
                'verbose_name_plural': 'Категории тестов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single', 'Один вариант'), ('multiple', 'Несколько вариантов'), ('text', 'Текстовый ответ')], default='single', max_length=20, verbose_name='Тип вопроса')),
                ('points', models.IntegerField(default=1, verbose_name='Баллы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('question_level', models.CharField(choices=[('basic', 'Базовый'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20, verbose_name='Уровень')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_questions', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20, verbose_name='Сложность')),
                ('time_limit', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(60)], verbose_name='Лимит времени (секунд)')),
                ('passing_score', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Проходной балл (%)')),
                ('access_type', models.CharField(choices=[('simple', 'Обычный'), ('subscribed', 'Назначенный')], default='simple', max_length=20, verbose_name='Тип доступа')),
                ('max_attempts', models.IntegerField(default=1, help_text='0 - без ограничений', verbose_name='Макс. попыток')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало доступа')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание доступа')),
                ('is_strict_mode', models.BooleanField(default=True, help_text='Запрет на возврат к предыдущим вопросам', verbose_name='Строгий режим')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Перемешивать вопросы')),
                ('shuffle_answers', models.BooleanField(default=False, verbose_name='Перемешивать ответы')),
                ('is_trial', models.BooleanField(default=False, help_text='Максимум 2 попытки', verbose_name='Пробный тест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='tests.testcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('percentage', models.FloatField(default=0, verbose_name='Процент')),
                ('passed', models.BooleanField(default=False, verbose_name='Сдано')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('time_taken', models.IntegerField(blank=True, null=True, verbose_name='Затрачено времени (сек)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.test', verbose_name='Тест')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Доступен с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Доступен до')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tests.test', verbose_name='Тест')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на тест',
                'verbose_name_plural': 'Подписки на тесты',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testresult', verbose_name='Результат')),
                ('selected_answers', models.ManyToManyField(blank=True, to='tests.answer', verbose_name='Выбранные ответы')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['category', 'difficulty'], name='tests_test_categor_849249_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active', 'created_at'], name='tests_test_is_acti_3b56a9_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['worker', 'test', '-completed_at'], name='tests_testr_worker__3c9566_idx'),
        ),
        migrations.AddIndex(
            model_name='testsubscription',
            index=models.Index(fields=['worker', 'valid_until'], name='tests_tests_worker__903066_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testsubscription',
            unique_together={('worker', 'test')},
        ),
    ]
