# Generated by Django 6.0.2 on 2026-02-28 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test', 'id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='tests_test_categor_849249_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='tests_test_is_acti_3b56a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='testresult',
            name='tests_testr_worker__3c9566_idx',
        ),
        migrations.RemoveIndex(
            model_name='testsubscription',
            name='tests_tests_worker__903066_idx',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='access_type',
            field=models.CharField(choices=[('simple', 'Обычный'), ('subscribed', 'По подписке')], default='simple', max_length=20, verbose_name='Тип доступа'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_strict_mode',
            field=models.BooleanField(default=True, verbose_name='Строгий режим'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Пробный тест'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='0 - без ограничений', verbose_name='Максимум попыток'),
        ),
        migrations.AlterField(
            model_name='test',
            name='passing_score',
            field=models.IntegerField(default=70, verbose_name='Проходной балл (%)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=3600, verbose_name='Лимит времени (сек)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsubscription',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='testsubscription',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testresult'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answers',
            field=models.ManyToManyField(blank=True, to='tests.answer'),
        ),
        migrations.RemoveField(
            model_name='test',
            name='updated_at',
        ),
    ]
